server:
  port: 8082

app:
  upload-dir: uploads

spring:
  application:
    name: user-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:postgresql://localhost:5432/user_service_db
    username: postgres
    password: Iset14418555* #badrix bellahi chouf louta
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   #badrix taw takhrali fih
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/symptomcheck-realm

# ===============================
# üîê Keycloak Admin Configuration
# ===============================
keycloak:
  admin:
    server-url: http://localhost:8080
    realm: master
    username: admin
    password: admin
    client-id: admin-cli
  app:
    realm: symptomcheck-realm
    client-id: userservice
    client-secret: userservice-secret
    roles: USER,ADMIN,DOCTOR,PATIENT

# ===============================
# ü©∫ Monitoring (Optional)
# ===============================
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# ===============================
#  Logging Levels
# ===============================
logging:
  level:
    com.SymptomCheck.userservice: DEBUG
    org.keycloak: INFO
    org.springframework.security: DEBUG






