# =========================
# Userservice NodePort Service
# =========================
apiVersion: v1
kind: Service
metadata:
  name: userservice-nodeport
  namespace: symptomcheck-backend
spec:
  type: NodePort
  selector:
    app: userservice
  ports:
    - name: http
      port: 80
      targetPort: 8082
      nodePort: 32081