
include:
 # - local: 'SymptomCheck-backend/clinicservice/.gitlab-ci.yml'
 # - local: 'SymptomCheck-backend/reviewservice/.gitlab-ci.yml'
   - local: 'SymptomCheck-backend/doctorservice/.gitlab-ci.yml'

  
