# helm/values/kube-prometheus-values.yaml (testing / ephemeral)
prometheus:
  prometheusSpec:
    # use ephemeral storage instead of PVCs (for testing only)
    storageSpec:
      emptyDir: {}

alertmanager:
  enabled: true
  alertmanagerSpec:
    # ephemeral storage for alertmanager
    storage:
      emptyDir: {}

grafana:
  enabled: true
  adminUser: admin
  adminPassword: "ChangeMeStrongPassword!"
  persistence:
    enabled: false
