apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointmentservice
  namespace: symptomcheck-backend
  labels:
    app: clinicservice
spec:
  replicas: 10
  selector:
    matchLabels:
      app: clinicservice
  template:
    metadata:
      labels:
        app: clinicservice
    spec:
      containers:
        - name: clinicservice
          image: amir254/appointmentservice:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8089

          envFrom:
            - configMapRef:
                name: symptomcheck-backend-db-config
            - secretRef:
                name: symptomcheck-backend-db-secret

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8089
            initialDelaySeconds: 15
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8089
            initialDelaySeconds: 30
            periodSeconds: 20
