apiVersion: v1
kind: Service
metadata:
  name: appointment-nodeport
  namespace: symptomcheck-backend
spec:
  type: NodePort
  selector:
    app: appointmentservice
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 32089