apiVersion: v1
kind: Service
metadata:
  name: appointmentservice
  namespace: symptomcheck-backend
spec:
  type: ClusterIP
  selector:
    app: clinicservice
  ports:
    - port: 80
      targetPort: 8089
