apiVersion: v1
kind: Service
metadata:
  name: doctorservice-nodeport
  namespace: symptomcheck-backend
spec:
  type: NodePort
  selector:
    app: doctorservice
  ports:
    - name: http
      port: 80
      targetPort: 8085
      nodePort: 32082
