apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinicservice
  namespace: symptomcheck-backend
  labels:
    app: clinicservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clinicservice
  template:
    metadata:
      labels:
        app: clinicservice
    spec:
      resources:
        requests:
          cpu: "250m"
          memory: "512Mi"
        limits:
          cpu: "500m"
          memory: "1Gi"
      containers:
        - name: clinicservice
          image: amir254/clinicservice:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8085

          envFrom:
            - configMapRef:
                name: symptomcheck-backend-db-config
            - secretRef:
                name: symptomcheck-backend-db-secret


