apiVersion: v1
kind: Service
metadata:
  name: clinicservice-nodeport
  namespace: symptomcheck-backend
spec:
  type: NodePort
  selector:
    app: clinicservice
  ports:
    - name: http
      port: 80
      targetPort: 8085
      nodePort: 32084