apiVersion: v1
kind: Secret
metadata:
  name: symptomcheck-backend-db-secret
  namespace: symptomcheck-backend
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: PostgresPwd99$
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin123"