apiVersion: v1
kind: Service
metadata:
  name: my-angular-app
  namespace: symptomcheck-frontend
spec:
  type: ClusterIP
  selector:
    app: my-angular-app
  ports:
    - name: http
      port: 80
      targetPort: 80
